[package]
name = "cloudtoid-interprocess-python"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Python bindings for Cloudtoid Interprocess"

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
core-queue = { package = "cloudtoid-interprocess", path = "../rust", version = "3.0.0" }
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py39"] }

[build-dependencies]
pyo3-build-config = "0.29"
