from os import PathLike
from types import TracebackType
from typing import Any, Iterable, Optional, Type, Union

__version__: str
class InterprocessError(Exception): ...
class CapacityMismatchError(InterprocessError, ValueError): ...
class PublisherLimitError(InterprocessError, RuntimeError): ...
class CorruptQueueError(InterprocessError, RuntimeError): ...
class Publisher:
    def __init__(self, name: str, capacity: int, path: Optional[Union[str, PathLike[str]]] = ...) -> None: ...
    def try_send(self, data: Any) -> bool: ...  # Any object implementing the buffer protocol.
    def try_send_batch(self, messages: Iterable[Any]) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> Publisher: ...
    def __exit__(self, kind: Optional[Type[BaseException]], value: Optional[BaseException], traceback: Optional[TracebackType]) -> None: ...
class Subscriber:
    def __init__(self, name: str, capacity: int, path: Optional[Union[str, PathLike[str]]] = ...) -> None: ...
    def try_receive(self) -> Optional[bytes]: ...
    def receive(self, timeout: Optional[float] = ...) -> Optional[bytes]: ...
    def close(self) -> None: ...
    def __enter__(self) -> Subscriber: ...
    def __exit__(self, kind: Optional[Type[BaseException]], value: Optional[BaseException], traceback: Optional[TracebackType]) -> None: ...
