[package]
name = "cloudtoid-interprocess-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://cloudtoid.com/docs/c/"
authors.workspace = true
description = "C ABI for Cloudtoid Interprocess shared-memory queues"

[lib]
name = "cloudtoid_interprocess"
crate-type = ["cdylib", "staticlib"]

[dependencies]
core-queue = { package = "cloudtoid-interprocess", path = "../rust", version = "3.0.2" }
