[package]
name = "cloudtoid-interprocess-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
core-queue = { package = "cloudtoid-interprocess", path = "../rust", version = "3.0.0" }
napi = { version = "3", default-features = false, features = ["napi8"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"
