name: publish

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: Build Test Pack and Publish
    steps:

      - name: Checkout
        uses: actions/checkout@v7
   
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            10.0.x

      - name: Test - Debug
        run: dotnet test src/Interprocess.sln

      - name: Test - Release
        run: dotnet test -c Release -p:VersionSuffix=${{github.run_number}} src/Interprocess.sln

      - name: Pack
        run: dotnet pack -c Release --no-build --output . --version-suffix ${{github.run_number}} src/Interprocess/Interprocess.csproj 

      - name: NuGet login
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: pedramr

      - name: Push
        run: dotnet nuget push Cloudtoid.Interprocess.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }}